import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pydot
from unidecode import unidecode
import graphviz


class Bairro:
    def __init__(self, cod, nome):
        self.cod = cod
        self.nome = nome

        self.S = 3000
        self.I = 300
        self.R = 0
        self.X = 0
        
        #self.taxa_virulencia = 29/200
        #self.taxa_recuperaçao = 91/200

        #self.taxa_distanciamento = 0

    def __repr__(self):
        return f"{self.nome}"#\nS: {self.S}\nI: {self.I}\nR: {self.R}"

class TextTransform:
    def __init__(self, arq, arq_adj):
        self.arquivo = open(arq, "r", encoding="utf8")
        self.arquivo_adj  = open(arq_adj, "r", encoding="utf8")

        self.num_bairros = {}

    def NumCidades(self):
        instancias_cidades = ""
        #node_cidades = ""
        #lista_cidades = []
        self.num_bairros = {}
        
        for linha in self.arquivo:
            linha = linha.strip()

            if linha != "":
                num, bairro = linha.split(" ", maxsplit=1)
                num = int(num)

                nome = unidecode(bairro.lower()).replace(" ", "_")

                self.num_bairros[num] = nome
                instancias_cidades += f"{nome} = Bairro({num}, '{bairro}')\nG.add_node({nome})\n"


                #lista_cidades.append((num, bairro))
                #node_cidades += f""

        return instancias_cidades


    def AdjCidades(self):
        bairros_adjs = []
        cidades_ja_visitadas = set()

        for i, linha in enumerate(self.arquivo_adj):
            linha = linha.strip()
            
            if linha != "":
                num_bairro = linha.split(" ", maxsplit=1)[0]
                num_bairro = int(num_bairro)

                if num_bairro not in cidades_ja_visitadas:
                    cidades_ja_visitadas.add(num_bairro)

                    adjs = [int(x) for x in linha.split(" ")[1:]]
                    for cidade in adjs:
                        if cidade in cidades_ja_visitadas:
                            adjs.remove(cidade)


                    bairros_adjs.append((num_bairro, adjs))
        
        texto_adj = ""

        for bairro, adjs in bairros_adjs:
            #print(bairro,adjs)
            nome_bairro = self.num_bairros[bairro]
            if adjs != []:
                for adj in adjs:
                    nome_adjacente = self.num_bairros[adj]

                    texto_adj += f"G.add_edge({nome_bairro}, {nome_adjacente})\n"
        
        return texto_adj


G = nx.Graph()

saude = Bairro(1, 'Saúde')
G.add_node(saude)
gamboa = Bairro(2, 'Gamboa')
G.add_node(gamboa)
santo_cristo = Bairro(3, 'Santo Cristo')
G.add_node(santo_cristo)
caju = Bairro(4, 'Caju')
G.add_node(caju)
centro = Bairro(5, 'Centro')
G.add_node(centro)
lapa = Bairro(161, 'Lapa')
G.add_node(lapa)
catumbi = Bairro(6, 'Catumbi')
G.add_node(catumbi)
rio_comprido = Bairro(7, 'Rio Comprido')
G.add_node(rio_comprido)
cidade_nova = Bairro(8, 'Cidade Nova')
G.add_node(cidade_nova)
estacio = Bairro(9, 'Estácio')
G.add_node(estacio)
imperial_de_sao_cristovao = Bairro(10, 'Imperial de São Cristóvão')
G.add_node(imperial_de_sao_cristovao)
mangueira = Bairro(11, 'Mangueira')
G.add_node(mangueira)
benfica = Bairro(12, 'Benfica')
G.add_node(benfica)
vasco_da_gama = Bairro(158, 'Vasco da Gama')
G.add_node(vasco_da_gama)
paqueta = Bairro(13, 'Paquetá')
G.add_node(paqueta)
santa_teresa = Bairro(14, 'Santa Teresa')
G.add_node(santa_teresa)
flamengo = Bairro(15, 'Flamengo')
G.add_node(flamengo)
gloria = Bairro(16, 'Glória')
G.add_node(gloria)
laranjeiras = Bairro(17, 'Laranjeiras')
G.add_node(laranjeiras)
catete = Bairro(18, 'Catete')
G.add_node(catete)
cosme_velho = Bairro(19, 'Cosme Velho')
G.add_node(cosme_velho)
botafogo = Bairro(20, 'Botafogo')
G.add_node(botafogo)
humaita = Bairro(21, 'Humaitá')
G.add_node(humaita)
urca = Bairro(22, 'Urca')
G.add_node(urca)
leme = Bairro(23, 'Leme')
G.add_node(leme)
copacabana = Bairro(24, 'Copacabana')
G.add_node(copacabana)
ipanema = Bairro(25, 'Ipanema')
G.add_node(ipanema)
leblon = Bairro(26, 'Leblon')
G.add_node(leblon)
lagoa = Bairro(27, 'Lagoa')
G.add_node(lagoa)
jardim_botanico = Bairro(28, 'Jardim Botânico')
G.add_node(jardim_botanico)
gavea = Bairro(29, 'Gávea')
G.add_node(gavea)
vidigal = Bairro(30, 'Vidigal')
G.add_node(vidigal)
sao_conrado = Bairro(31, 'São Conrado')
G.add_node(sao_conrado)
rocinha = Bairro(154, 'Rocinha')
G.add_node(rocinha)
praca_da_bandeira = Bairro(32, 'Praça da Bandeira')
G.add_node(praca_da_bandeira)
tijuca = Bairro(33, 'Tijuca')
G.add_node(tijuca)
alto_da_boa_vista = Bairro(34, 'Alto da Boa Vista')
G.add_node(alto_da_boa_vista)
maracana = Bairro(35, 'Maracanã')
G.add_node(maracana)
vila_isabel = Bairro(36, 'Vila Isabel')
G.add_node(vila_isabel)
andarai = Bairro(37, 'Andaraí')
G.add_node(andarai)
grajau = Bairro(38, 'Grajaú')
G.add_node(grajau)
manguinhos = Bairro(39, 'Manguinhos')
G.add_node(manguinhos)
bonsucesso = Bairro(40, 'Bonsucesso')
G.add_node(bonsucesso)
ramos = Bairro(41, 'Ramos')
G.add_node(ramos)
olaria = Bairro(42, 'Olaria')
G.add_node(olaria)
mare = Bairro(157, 'Mare')
G.add_node(mare)
jacare = Bairro(51, 'Jacaré')
G.add_node(jacare)
sao_francisco_xavier = Bairro(57, 'São Francisco Xavier')
G.add_node(sao_francisco_xavier)
rocha = Bairro(58, 'Rocha')
G.add_node(rocha)
riachuelo = Bairro(59, 'Riachuelo')
G.add_node(riachuelo)
sampaio = Bairro(60, 'Sampaio')
G.add_node(sampaio)
engenho_novo = Bairro(61, 'Engenho Novo')
G.add_node(engenho_novo)
lins_de_vasconcelos = Bairro(62, 'Lins de Vasconcelos')
G.add_node(lins_de_vasconcelos)
meier = Bairro(63, 'Méier')
G.add_node(meier)
todos_os_santos = Bairro(64, 'Todos os Santos')
G.add_node(todos_os_santos)
cachambi = Bairro(65, 'Cachambi')
G.add_node(cachambi)
engenho_de_dentro = Bairro(66, 'Engenho de Dentro')
G.add_node(engenho_de_dentro)
agua_santa = Bairro(67, 'Água Santa')
G.add_node(agua_santa)
encantado = Bairro(68, 'Encantado')
G.add_node(encantado)
piedade = Bairro(69, 'Piedade')
G.add_node(piedade)
abolicao = Bairro(70, 'Abolição')
G.add_node(abolicao)
pilares = Bairro(71, 'Pilares')
G.add_node(pilares)
jacarezinho = Bairro(155, 'Jacarezinho')
G.add_node(jacarezinho)
vila_kosmos = Bairro(72, 'Vila Kosmos')
G.add_node(vila_kosmos)
vicente_de_carvalho = Bairro(73, 'Vicente de Carvalho')
G.add_node(vicente_de_carvalho)
vila_da_penha = Bairro(74, 'Vila da Penha')
G.add_node(vila_da_penha)
vista_alegre = Bairro(75, 'Vista Alegre')
G.add_node(vista_alegre)
iraja = Bairro(76, 'Irajá')
G.add_node(iraja)
colegio = Bairro(77, 'Colégio')
G.add_node(colegio)
campinho = Bairro(78, 'Campinho')
G.add_node(campinho)
quintino_bocaiuva = Bairro(79, 'Quintino Bocaiuva')
G.add_node(quintino_bocaiuva)
cavalcanti = Bairro(80, 'Cavalcanti')
G.add_node(cavalcanti)
engenheiro_leal = Bairro(81, 'Engenheiro Leal')
G.add_node(engenheiro_leal)
cascadura = Bairro(82, 'Cascadura')
G.add_node(cascadura)
madureira = Bairro(83, 'Madureira')
G.add_node(madureira)
vaz_lobo = Bairro(84, 'Vaz Lobo')
G.add_node(vaz_lobo)
turiacu = Bairro(85, 'Turiaçu')
G.add_node(turiacu)
rocha_miranda = Bairro(86, 'Rocha Miranda')
G.add_node(rocha_miranda)
honorio_gurgel = Bairro(87, 'Honório Gurgel')
G.add_node(honorio_gurgel)
oswaldo_cruz = Bairro(88, 'Oswaldo Cruz')
G.add_node(oswaldo_cruz)
bento_ribeiro = Bairro(89, 'Bento Ribeiro')
G.add_node(bento_ribeiro)
marechal_hermes = Bairro(90, 'Marechal Hermes')
G.add_node(marechal_hermes)
higienopolis = Bairro(50, 'Higienópolis')
G.add_node(higienopolis)
maria_da_graca = Bairro(52, 'Maria da Graça')
G.add_node(maria_da_graca)
del_castilho = Bairro(53, 'Del Castilho')
G.add_node(del_castilho)
inhauma = Bairro(54, 'Inhaúma')
G.add_node(inhauma)
engenho_da_rainha = Bairro(55, 'Engenho da Rainha')
G.add_node(engenho_da_rainha)
tomas_coelho = Bairro(56, 'Tomás Coelho')
G.add_node(tomas_coelho)
complexo_do_alemao = Bairro(156, 'Complexo do Alemão')
G.add_node(complexo_do_alemao)
penha = Bairro(43, 'Penha')
G.add_node(penha)
penha_circular = Bairro(44, 'Penha Circular')
G.add_node(penha_circular)
braz_de_pina = Bairro(45, 'Braz de Pina')
G.add_node(braz_de_pina)
cordovil = Bairro(46, 'Cordovil')
G.add_node(cordovil)
parada_de_lucas = Bairro(47, 'Parada de Lucas')
G.add_node(parada_de_lucas)
vigario_geral = Bairro(48, 'Vigário Geral')
G.add_node(vigario_geral)
jardim_america = Bairro(49, 'Jardim América')
G.add_node(jardim_america)
guadalupe = Bairro(106, 'Guadalupe')
G.add_node(guadalupe)
anchieta = Bairro(107, 'Anchieta')
G.add_node(anchieta)
parque_anchieta = Bairro(108, 'Parque Anchieta')
G.add_node(parque_anchieta)
ricardo_de_albuquerque = Bairro(109, 'Ricardo de Albuquerque')
G.add_node(ricardo_de_albuquerque)
coelho_neto = Bairro(110, 'Coelho Neto')
G.add_node(coelho_neto)
acari = Bairro(111, 'Acari')
G.add_node(acari)
barros_filho = Bairro(112, 'Barros Filho')
G.add_node(barros_filho)
costa_barros = Bairro(113, 'Costa BarroS')
G.add_node(costa_barros)
pavuna = Bairro(114, 'Pavuna')
G.add_node(pavuna)
parque_columbia = Bairro(159, 'Parque Columbia')
G.add_node(parque_columbia)
ribeira = Bairro(91, 'Ribeira')
G.add_node(ribeira)
zumbi = Bairro(92, 'Zumbi')
G.add_node(zumbi)
cacuia = Bairro(93, 'Cacuia')
G.add_node(cacuia)
pitangueiras = Bairro(94, 'Pitangueiras')
G.add_node(pitangueiras)
praia_da_bandeira = Bairro(95, 'Praia da Bandeira')
G.add_node(praia_da_bandeira)
cocota = Bairro(96, 'Cocotá')
G.add_node(cocota)
bancarios = Bairro(97, 'Bancários')
G.add_node(bancarios)
freguesia = Bairro(98, 'Freguesia (Ilha do Gov.)')
G.add_node(freguesia)
jardim_guanabara = Bairro(99, 'Jardim Guanabara')
G.add_node(jardim_guanabara)
jardim_carioca = Bairro(100, 'Jardim Carioca')
G.add_node(jardim_carioca)
taua = Bairro(101, 'Tauá')
G.add_node(taua)
monero = Bairro(102, 'Moneró')
G.add_node(monero)
portuguesa = Bairro(103, 'Portuguesa')
G.add_node(portuguesa)
galeao = Bairro(104, 'Galeão')
G.add_node(galeao)
cidade_universitaria = Bairro(105, 'Cidade Universitária')
G.add_node(cidade_universitaria)
jacarepagua = Bairro(115, 'Jacarepaguá')
G.add_node(jacarepagua)
anil = Bairro(116, 'Anil')
G.add_node(anil)
gardenia_azul = Bairro(117, 'Gardênia Azul')
G.add_node(gardenia_azul)
curicica = Bairro(119, 'Curicica')
G.add_node(curicica)
freguesia2 = Bairro(120, 'Freguesia')
G.add_node(freguesia2)
pechincha = Bairro(121, 'Pechincha')
G.add_node(pechincha)
taquara = Bairro(122, 'Taquara')
G.add_node(taquara)
tanque = Bairro(123, 'Tanque')
G.add_node(tanque)
praca_seca = Bairro(124, 'Praça Seca')
G.add_node(praca_seca)
vila_valqueire = Bairro(125, 'Vila Valqueire')
G.add_node(vila_valqueire)
cidade_de_deus = Bairro(118, 'Cidade de Deus')
G.add_node(cidade_de_deus)
joa = Bairro(126, 'Joá')
G.add_node(joa)
itanhanga = Bairro(127, 'Itanhangá')
G.add_node(itanhanga)
barra_da_tijuca = Bairro(128, 'Barra da Tijuca')
G.add_node(barra_da_tijuca)
camorim = Bairro(129, 'Camorim')
G.add_node(camorim)
vargem_pequena = Bairro(130, 'Vargem Pequena')
G.add_node(vargem_pequena)
vargem_grande = Bairro(131, 'Vargem Grande')
G.add_node(vargem_grande)
recreio_dos_bandeirantes = Bairro(132, 'Recreio dos Bandeirantes')
G.add_node(recreio_dos_bandeirantes)
grumari = Bairro(133, 'Grumari')
G.add_node(grumari)
padre_miguel = Bairro(140, 'Padre Miguel')
G.add_node(padre_miguel)
bangu = Bairro(141, 'Bangu')
G.add_node(bangu)
senador_camara = Bairro(142, 'Senador Camará')
G.add_node(senador_camara)
gericino = Bairro(160, 'Gericinó')
G.add_node(gericino)
vila_kennedy = Bairro(162, 'Vila Kennedy')
G.add_node(vila_kennedy)
jabour = Bairro(163, 'Jabour')
G.add_node(jabour)
deodoro = Bairro(134, 'Deodoro')
G.add_node(deodoro)
vila_militar = Bairro(135, 'Vila Militar')
G.add_node(vila_militar)
campo_dos_afonsos = Bairro(136, 'Campo dos Afonsos')
G.add_node(campo_dos_afonsos)
jardim_sulacap = Bairro(137, 'Jardim Sulacap')
G.add_node(jardim_sulacap)
magalhaes_bastos = Bairro(138, 'Magalhães Bastos')
G.add_node(magalhaes_bastos)
realengo = Bairro(139, 'Realengo')
G.add_node(realengo)
santissimo = Bairro(143, 'Santíssimo')
G.add_node(santissimo)
campo_grande = Bairro(144, 'Campo Grande')
G.add_node(campo_grande)
senador_vasconcelos = Bairro(145, 'Senador Vasconcelos')
G.add_node(senador_vasconcelos)
inhoaiba = Bairro(146, 'Inhoaíba')
G.add_node(inhoaiba)
cosmos = Bairro(147, 'Cosmos')
G.add_node(cosmos)
paciencia = Bairro(148, 'Paciência')
G.add_node(paciencia)
santa_cruz = Bairro(149, 'Santa Cruz')
G.add_node(santa_cruz)
sepetiba = Bairro(150, 'Sepetiba')
G.add_node(sepetiba)
guaratiba = Bairro(151, 'Guaratiba')
G.add_node(guaratiba)
barra_de_guaratiba = Bairro(152, 'Barra de Guaratiba')
G.add_node(barra_de_guaratiba)
pedra_de_guaratiba = Bairro(153, 'Pedra de Guaratiba')
G.add_node(pedra_de_guaratiba)
G.add_edge(saude, gamboa)
G.add_edge(saude, centro)
G.add_edge(gamboa, santo_cristo)
G.add_edge(gamboa, centro)
G.add_edge(santo_cristo, cidade_nova)
G.add_edge(santo_cristo, imperial_de_sao_cristovao)
G.add_edge(santo_cristo, praca_da_bandeira)
G.add_edge(caju, vasco_da_gama)
G.add_edge(caju, imperial_de_sao_cristovao)
G.add_edge(caju, benfica)
G.add_edge(caju, manguinhos)
G.add_edge(caju, mare)
G.add_edge(centro, gamboa)
G.add_edge(centro, cidade_nova)
G.add_edge(centro, lapa)
G.add_edge(catumbi, lapa)
G.add_edge(catumbi, cidade_nova)
G.add_edge(catumbi, estacio)
G.add_edge(catumbi, rio_comprido)
G.add_edge(rio_comprido, estacio)
G.add_edge(rio_comprido, praca_da_bandeira)
G.add_edge(rio_comprido, tijuca)
G.add_edge(rio_comprido, alto_da_boa_vista)
G.add_edge(rio_comprido, cosme_velho)
G.add_edge(rio_comprido, lapa)
G.add_edge(cidade_nova, estacio)
G.add_edge(cidade_nova, centro)
G.add_edge(cidade_nova, praca_da_bandeira)
G.add_edge(estacio, catumbi)
G.add_edge(estacio, praca_da_bandeira)
G.add_edge(imperial_de_sao_cristovao, praca_da_bandeira)
G.add_edge(imperial_de_sao_cristovao, maracana)
G.add_edge(imperial_de_sao_cristovao, mangueira)
G.add_edge(imperial_de_sao_cristovao, vasco_da_gama)
G.add_edge(imperial_de_sao_cristovao, benfica)
G.add_edge(mangueira, benfica)
G.add_edge(mangueira, sao_francisco_xavier)
G.add_edge(mangueira, maracana)
G.add_edge(benfica, vasco_da_gama)
G.add_edge(benfica, manguinhos)
G.add_edge(benfica, rocha)
G.add_edge(benfica, sao_francisco_xavier)
G.add_edge(benfica, imperial_de_sao_cristovao)
G.add_edge(benfica, jacarezinho)
G.add_edge(benfica, jacare)
G.add_edge(santa_teresa, cosme_velho)
G.add_edge(santa_teresa, humaita)
G.add_edge(santa_teresa, botafogo)
G.add_edge(santa_teresa, alto_da_boa_vista)
G.add_edge(santa_teresa, catumbi)
G.add_edge(santa_teresa, lapa)
G.add_edge(santa_teresa, gloria)
G.add_edge(santa_teresa, catete)
G.add_edge(santa_teresa, laranjeiras)
G.add_edge(flamengo, gloria)
G.add_edge(flamengo, catete)
G.add_edge(flamengo, laranjeiras)
G.add_edge(flamengo, botafogo)
G.add_edge(gloria, lapa)
G.add_edge(gloria, catete)
G.add_edge(gloria, centro)
G.add_edge(laranjeiras, catete)
G.add_edge(laranjeiras, botafogo)
G.add_edge(laranjeiras, cosme_velho)
G.add_edge(catete, gloria)
G.add_edge(catete, santa_teresa)
G.add_edge(cosme_velho, santa_teresa)
G.add_edge(botafogo, urca)
G.add_edge(botafogo, humaita)
G.add_edge(botafogo, copacabana)
G.add_edge(botafogo, flamengo)
G.add_edge(humaita, lagoa)
G.add_edge(humaita, jardim_botanico)
G.add_edge(leme, copacabana)
G.add_edge(copacabana, botafogo)
G.add_edge(copacabana, lagoa)
G.add_edge(copacabana, ipanema)
G.add_edge(ipanema, lagoa)
G.add_edge(ipanema, leblon)
G.add_edge(leblon, lagoa)
G.add_edge(leblon, gavea)
G.add_edge(leblon, vidigal)
G.add_edge(lagoa, humaita)
G.add_edge(lagoa, jardim_botanico)
G.add_edge(lagoa, gavea)
G.add_edge(jardim_botanico, lagoa)
G.add_edge(jardim_botanico, gavea)
G.add_edge(jardim_botanico, alto_da_boa_vista)
G.add_edge(gavea, lagoa)
G.add_edge(gavea, vidigal)
G.add_edge(gavea, rocinha)
G.add_edge(vidigal, gavea)
G.add_edge(vidigal, rocinha)
G.add_edge(vidigal, sao_conrado)
G.add_edge(sao_conrado, rocinha)
G.add_edge(sao_conrado, joa)
G.add_edge(praca_da_bandeira, cidade_nova)
G.add_edge(praca_da_bandeira, imperial_de_sao_cristovao)
G.add_edge(praca_da_bandeira, maracana)
G.add_edge(praca_da_bandeira, tijuca)
G.add_edge(tijuca, rio_comprido)
G.add_edge(tijuca, alto_da_boa_vista)
G.add_edge(tijuca, maracana)
G.add_edge(tijuca, vila_isabel)
G.add_edge(tijuca, andarai)
G.add_edge(alto_da_boa_vista, rio_comprido)
G.add_edge(maracana, imperial_de_sao_cristovao)
G.add_edge(maracana, vila_isabel)
G.add_edge(maracana, sao_francisco_xavier)
G.add_edge(vila_isabel, sao_francisco_xavier)
G.add_edge(vila_isabel, rocha)
G.add_edge(vila_isabel, riachuelo)
G.add_edge(vila_isabel, sampaio)
G.add_edge(vila_isabel, engenho_novo)
G.add_edge(vila_isabel, grajau)
G.add_edge(vila_isabel, andarai)
G.add_edge(vila_isabel, tijuca)
G.add_edge(andarai, tijuca)
G.add_edge(andarai, grajau)
G.add_edge(grajau, vila_isabel)
G.add_edge(grajau, engenho_novo)
G.add_edge(grajau, lins_de_vasconcelos)
G.add_edge(manguinhos, mare)
G.add_edge(manguinhos, bonsucesso)
G.add_edge(manguinhos, higienopolis)
G.add_edge(manguinhos, jacare)
G.add_edge(manguinhos, maria_da_graca)
G.add_edge(bonsucesso, higienopolis)
G.add_edge(bonsucesso, complexo_do_alemao)
G.add_edge(bonsucesso, ramos)
G.add_edge(bonsucesso, mare)
G.add_edge(ramos, mare)
G.add_edge(ramos, olaria)
G.add_edge(ramos, complexo_do_alemao)
G.add_edge(olaria, mare)
G.add_edge(olaria, complexo_do_alemao)
G.add_edge(olaria, penha)
G.add_edge(olaria, engenho_da_rainha)
G.add_edge(penha, penha_circular)
G.add_edge(penha_circular, braz_de_pina)
G.add_edge(penha_circular, vila_kosmos)
G.add_edge(penha_circular, vila_da_penha)
G.add_edge(penha_circular, cordovil)
G.add_edge(braz_de_pina, cordovil)
G.add_edge(braz_de_pina, vila_da_penha)
G.add_edge(braz_de_pina, iraja)
G.add_edge(braz_de_pina, vista_alegre)
G.add_edge(cordovil, galeao)
G.add_edge(cordovil, parada_de_lucas)
G.add_edge(cordovil, braz_de_pina)
G.add_edge(cordovil, vista_alegre)
G.add_edge(parada_de_lucas, vigario_geral)
G.add_edge(parada_de_lucas, iraja)
G.add_edge(vigario_geral, jardim_america)
G.add_edge(jardim_america, iraja)
G.add_edge(jardim_america, pavuna)
G.add_edge(higienopolis, complexo_do_alemao)
G.add_edge(higienopolis, del_castilho)
G.add_edge(higienopolis, inhauma)
G.add_edge(jacare, jacarezinho)
G.add_edge(jacare, rocha)
G.add_edge(jacare, riachuelo)
G.add_edge(jacare, sampaio)
G.add_edge(maria_da_graca, del_castilho)
G.add_edge(maria_da_graca, cachambi)
G.add_edge(del_castilho, inhauma)
G.add_edge(del_castilho, cachambi)
G.add_edge(inhauma, complexo_do_alemao)
G.add_edge(inhauma, engenho_da_rainha)
G.add_edge(inhauma, pilares)
G.add_edge(inhauma, engenho_de_dentro)
G.add_edge(inhauma, cachambi)
G.add_edge(engenho_da_rainha, tomas_coelho)
G.add_edge(engenho_da_rainha, complexo_do_alemao)
G.add_edge(engenho_da_rainha, vila_kosmos)
G.add_edge(tomas_coelho, vila_kosmos)
G.add_edge(tomas_coelho, vicente_de_carvalho)
G.add_edge(tomas_coelho, cavalcanti)
G.add_edge(tomas_coelho, pilares)
G.add_edge(tomas_coelho, piedade)
G.add_edge(sao_francisco_xavier, benfica)
G.add_edge(sao_francisco_xavier, rocha)
G.add_edge(rocha, vila_isabel)
G.add_edge(rocha, sampaio)
G.add_edge(rocha, riachuelo)
G.add_edge(riachuelo, sampaio)
G.add_edge(riachuelo, vila_isabel)
G.add_edge(sampaio, jacare)
G.add_edge(sampaio, engenho_novo)
G.add_edge(engenho_novo, vila_isabel)
G.add_edge(engenho_novo, cachambi)
G.add_edge(engenho_novo, lins_de_vasconcelos)
G.add_edge(engenho_novo, meier)
G.add_edge(lins_de_vasconcelos, meier)
G.add_edge(lins_de_vasconcelos, engenho_de_dentro)
G.add_edge(lins_de_vasconcelos, jacarepagua)
G.add_edge(meier, cachambi)
G.add_edge(meier, todos_os_santos)
G.add_edge(meier, engenho_de_dentro)
G.add_edge(todos_os_santos, cachambi)
G.add_edge(todos_os_santos, engenho_de_dentro)
G.add_edge(cachambi, maria_da_graca)
G.add_edge(cachambi, engenho_de_dentro)
G.add_edge(cachambi, meier)
G.add_edge(cachambi, sampaio)
G.add_edge(cachambi, jacarezinho)
G.add_edge(engenho_de_dentro, cachambi)
G.add_edge(engenho_de_dentro, meier)
G.add_edge(engenho_de_dentro, agua_santa)
G.add_edge(engenho_de_dentro, encantado)
G.add_edge(engenho_de_dentro, abolicao)
G.add_edge(engenho_de_dentro, pilares)
G.add_edge(agua_santa, freguesia2)
G.add_edge(agua_santa, piedade)
G.add_edge(agua_santa, encantado)
G.add_edge(encantado, abolicao)
G.add_edge(encantado, piedade)
G.add_edge(piedade, quintino_bocaiuva)
G.add_edge(piedade, encantado)
G.add_edge(piedade, abolicao)
G.add_edge(abolicao, pilares)
G.add_edge(abolicao, encantado)
G.add_edge(pilares, engenho_da_rainha)
G.add_edge(pilares, piedade)
G.add_edge(pilares, engenho_de_dentro)
G.add_edge(vila_kosmos, engenho_da_rainha)
G.add_edge(vila_kosmos, vicente_de_carvalho)
G.add_edge(vila_kosmos, vila_da_penha)
G.add_edge(vicente_de_carvalho, vila_da_penha)
G.add_edge(vicente_de_carvalho, tomas_coelho)
G.add_edge(vicente_de_carvalho, cavalcanti)
G.add_edge(vicente_de_carvalho, vaz_lobo)
G.add_edge(vicente_de_carvalho, iraja)
G.add_edge(vila_da_penha, penha_circular)
G.add_edge(vila_da_penha, vicente_de_carvalho)
G.add_edge(vila_da_penha, iraja)
G.add_edge(vista_alegre, braz_de_pina)
G.add_edge(vista_alegre, iraja)
G.add_edge(iraja, vigario_geral)
G.add_edge(iraja, vista_alegre)
G.add_edge(iraja, vicente_de_carvalho)
G.add_edge(iraja, vaz_lobo)
G.add_edge(iraja, rocha_miranda)
G.add_edge(iraja, colegio)
G.add_edge(iraja, acari)
G.add_edge(colegio, coelho_neto)
G.add_edge(colegio, rocha_miranda)
G.add_edge(campinho, cascadura)
G.add_edge(campinho, praca_seca)
G.add_edge(campinho, vila_valqueire)
G.add_edge(campinho, oswaldo_cruz)
G.add_edge(campinho, madureira)
G.add_edge(quintino_bocaiuva, tanque)
G.add_edge(quintino_bocaiuva, praca_seca)
G.add_edge(quintino_bocaiuva, cascadura)
G.add_edge(quintino_bocaiuva, cavalcanti)
G.add_edge(quintino_bocaiuva, freguesia2)
G.add_edge(cavalcanti, piedade)
G.add_edge(cavalcanti, cascadura)
G.add_edge(cavalcanti, engenheiro_leal)
G.add_edge(cavalcanti, madureira)
G.add_edge(cavalcanti, vaz_lobo)
G.add_edge(engenheiro_leal, cascadura)
G.add_edge(engenheiro_leal, madureira)
G.add_edge(cascadura, cavalcanti)
G.add_edge(cascadura, madureira)
G.add_edge(cascadura, praca_seca)
G.add_edge(madureira, vaz_lobo)
G.add_edge(madureira, engenheiro_leal)
G.add_edge(madureira, campinho)
G.add_edge(madureira, oswaldo_cruz)
G.add_edge(madureira, turiacu)
G.add_edge(vaz_lobo, iraja)
G.add_edge(vaz_lobo, turiacu)
G.add_edge(vaz_lobo, cavalcanti)
G.add_edge(turiacu, rocha_miranda)
G.add_edge(turiacu, vaz_lobo)
G.add_edge(turiacu, oswaldo_cruz)
G.add_edge(rocha_miranda, colegio)
G.add_edge(rocha_miranda, honorio_gurgel)
G.add_edge(rocha_miranda, bento_ribeiro)
G.add_edge(honorio_gurgel, coelho_neto)
G.add_edge(honorio_gurgel, bento_ribeiro)
G.add_edge(honorio_gurgel, barros_filho)
G.add_edge(oswaldo_cruz, bento_ribeiro)
G.add_edge(oswaldo_cruz, campinho)
G.add_edge(bento_ribeiro, vila_valqueire)
G.add_edge(bento_ribeiro, marechal_hermes)
G.add_edge(bento_ribeiro, rocha_miranda)
G.add_edge(marechal_hermes, honorio_gurgel)
G.add_edge(marechal_hermes, guadalupe)
G.add_edge(marechal_hermes, deodoro)
G.add_edge(marechal_hermes, campo_dos_afonsos)
G.add_edge(marechal_hermes, vila_valqueire)
G.add_edge(ribeira, zumbi)
G.add_edge(zumbi, pitangueiras)
G.add_edge(zumbi, cacuia)
G.add_edge(cacuia, pitangueiras)
G.add_edge(cacuia, jardim_guanabara)
G.add_edge(cacuia, jardim_carioca)
G.add_edge(cacuia, cocota)
G.add_edge(cacuia, praia_da_bandeira)
G.add_edge(pitangueiras, praia_da_bandeira)
G.add_edge(pitangueiras, zumbi)
G.add_edge(praia_da_bandeira, cocota)
G.add_edge(praia_da_bandeira, cacuia)
G.add_edge(cocota, taua)
G.add_edge(cocota, jardim_carioca)
G.add_edge(cocota, bancarios)
G.add_edge(cocota, cacuia)
G.add_edge(bancarios, freguesia)
G.add_edge(bancarios, taua)
G.add_edge(jardim_guanabara, jardim_carioca)
G.add_edge(jardim_guanabara, galeao)
G.add_edge(jardim_guanabara, portuguesa)
G.add_edge(jardim_carioca, taua)
G.add_edge(jardim_carioca, cacuia)
G.add_edge(jardim_carioca, portuguesa)
G.add_edge(jardim_carioca, monero)
G.add_edge(taua, cocota)
G.add_edge(taua, monero)
G.add_edge(monero, jardim_carioca)
G.add_edge(monero, portuguesa)
G.add_edge(portuguesa, jardim_carioca)
G.add_edge(portuguesa, galeao)
G.add_edge(galeao, portuguesa)
G.add_edge(cidade_universitaria, mare)
G.add_edge(guadalupe, costa_barros)
G.add_edge(guadalupe, barros_filho)
G.add_edge(guadalupe, deodoro)
G.add_edge(guadalupe, ricardo_de_albuquerque)
G.add_edge(guadalupe, anchieta)
G.add_edge(anchieta, pavuna)
G.add_edge(anchieta, ricardo_de_albuquerque)
G.add_edge(anchieta, parque_anchieta)
G.add_edge(parque_anchieta, ricardo_de_albuquerque)
G.add_edge(parque_anchieta, vila_militar)
G.add_edge(parque_anchieta, realengo)
G.add_edge(ricardo_de_albuquerque, guadalupe)
G.add_edge(ricardo_de_albuquerque, deodoro)
G.add_edge(ricardo_de_albuquerque, vila_militar)
G.add_edge(coelho_neto, acari)
G.add_edge(coelho_neto, colegio)
G.add_edge(coelho_neto, honorio_gurgel)
G.add_edge(coelho_neto, barros_filho)
G.add_edge(coelho_neto, pavuna)
G.add_edge(acari, parque_columbia)
G.add_edge(acari, coelho_neto)
G.add_edge(barros_filho, pavuna)
G.add_edge(barros_filho, honorio_gurgel)
G.add_edge(barros_filho, costa_barros)
G.add_edge(costa_barros, pavuna)
G.add_edge(costa_barros, guadalupe)
G.add_edge(pavuna, parque_columbia)
G.add_edge(pavuna, barros_filho)
G.add_edge(pavuna, anchieta)
G.add_edge(jacarepagua, anil)
G.add_edge(jacarepagua, gardenia_azul)
G.add_edge(jacarepagua, curicica)
G.add_edge(jacarepagua, cidade_de_deus)
G.add_edge(jacarepagua, freguesia2)
G.add_edge(jacarepagua, taquara)
G.add_edge(jacarepagua, itanhanga)
G.add_edge(jacarepagua, barra_da_tijuca)
G.add_edge(jacarepagua, camorim)
G.add_edge(anil, gardenia_azul)
G.add_edge(anil, freguesia2)
G.add_edge(gardenia_azul, jacarepagua)
G.add_edge(gardenia_azul, cidade_de_deus)
G.add_edge(gardenia_azul, freguesia2)
G.add_edge(cidade_de_deus, freguesia2)
G.add_edge(cidade_de_deus, taquara)
G.add_edge(cidade_de_deus, gardenia_azul)
G.add_edge(curicica, taquara)
G.add_edge(freguesia2, anil)
G.add_edge(freguesia2, cidade_de_deus)
G.add_edge(freguesia2, pechincha)
G.add_edge(freguesia2, tanque)
G.add_edge(freguesia2, agua_santa)
G.add_edge(pechincha, taquara)
G.add_edge(pechincha, tanque)
G.add_edge(taquara, tanque)
G.add_edge(taquara, cidade_de_deus)
G.add_edge(taquara, jacarepagua)
G.add_edge(taquara, jardim_sulacap)
G.add_edge(tanque, praca_seca)
G.add_edge(tanque, vila_valqueire)
G.add_edge(tanque, pechincha)
G.add_edge(tanque, jardim_sulacap)
G.add_edge(praca_seca, cascadura)
G.add_edge(praca_seca, tanque)
G.add_edge(praca_seca, vila_valqueire)
G.add_edge(vila_valqueire, bento_ribeiro)
G.add_edge(vila_valqueire, praca_seca)
G.add_edge(vila_valqueire, jardim_sulacap)
G.add_edge(vila_valqueire, campo_dos_afonsos)
G.add_edge(joa, barra_da_tijuca)
G.add_edge(itanhanga, barra_da_tijuca)
G.add_edge(barra_da_tijuca, joa)
G.add_edge(barra_da_tijuca, camorim)
G.add_edge(barra_da_tijuca, vargem_pequena)
G.add_edge(barra_da_tijuca, recreio_dos_bandeirantes)
G.add_edge(camorim, vargem_pequena)
G.add_edge(camorim, recreio_dos_bandeirantes)
G.add_edge(camorim, vargem_grande)
G.add_edge(vargem_pequena, vargem_grande)
G.add_edge(vargem_pequena, recreio_dos_bandeirantes)
G.add_edge(vargem_grande, recreio_dos_bandeirantes)
G.add_edge(vargem_grande, guaratiba)
G.add_edge(vargem_grande, barra_de_guaratiba)
G.add_edge(recreio_dos_bandeirantes, vargem_pequena)
G.add_edge(recreio_dos_bandeirantes, grumari)
G.add_edge(recreio_dos_bandeirantes, barra_de_guaratiba)
G.add_edge(grumari, barra_de_guaratiba)
G.add_edge(deodoro, marechal_hermes)
G.add_edge(deodoro, campo_dos_afonsos)
G.add_edge(deodoro, vila_militar)
G.add_edge(vila_militar, campo_dos_afonsos)
G.add_edge(vila_militar, jardim_sulacap)
G.add_edge(vila_militar, realengo)
G.add_edge(vila_militar, magalhaes_bastos)
G.add_edge(vila_militar, ricardo_de_albuquerque)
G.add_edge(campo_dos_afonsos, vila_valqueire)
G.add_edge(campo_dos_afonsos, jardim_sulacap)
G.add_edge(campo_dos_afonsos, deodoro)
G.add_edge(jardim_sulacap, tanque)
G.add_edge(jardim_sulacap, realengo)
G.add_edge(magalhaes_bastos, realengo)
G.add_edge(realengo, magalhaes_bastos)
G.add_edge(realengo, parque_anchieta)
G.add_edge(realengo, padre_miguel)
G.add_edge(realengo, bangu)
G.add_edge(padre_miguel, bangu)
G.add_edge(bangu, gericino)
G.add_edge(bangu, vila_kennedy)
G.add_edge(bangu, senador_camara)
G.add_edge(senador_camara, jabour)
G.add_edge(senador_camara, campo_grande)
G.add_edge(senador_camara, senador_vasconcelos)
G.add_edge(senador_camara, santissimo)
G.add_edge(santissimo, bangu)
G.add_edge(santissimo, senador_vasconcelos)
G.add_edge(santissimo, campo_grande)
G.add_edge(campo_grande, senador_vasconcelos)
G.add_edge(campo_grande, bangu)
G.add_edge(campo_grande, inhoaiba)
G.add_edge(campo_grande, cosmos)
G.add_edge(campo_grande, paciencia)
G.add_edge(campo_grande, guaratiba)
G.add_edge(senador_vasconcelos, senador_camara)
G.add_edge(inhoaiba, cosmos)
G.add_edge(cosmos, campo_grande)
G.add_edge(cosmos, paciencia)
G.add_edge(paciencia, santa_cruz)
G.add_edge(paciencia, campo_grande)
G.add_edge(santa_cruz, guaratiba)
G.add_edge(santa_cruz, sepetiba)
G.add_edge(sepetiba, guaratiba)
G.add_edge(guaratiba, pedra_de_guaratiba)
G.add_edge(guaratiba, barra_de_guaratiba)
G.add_edge(guaratiba, santa_cruz)
G.add_edge(barra_de_guaratiba, grumari)
G.add_edge(barra_de_guaratiba, vargem_grande)
G.add_edge(rocinha, sao_conrado)
G.add_edge(jacarezinho, maria_da_graca)
G.add_edge(jacarezinho, jacare)
G.add_edge(complexo_do_alemao, ramos)
G.add_edge(complexo_do_alemao, higienopolis)
G.add_edge(complexo_do_alemao, engenho_da_rainha)
G.add_edge(mare, ramos)
G.add_edge(mare, manguinhos)
G.add_edge(vasco_da_gama, benfica)
G.add_edge(parque_columbia, acari)
G.add_edge(lapa, centro)
G.add_edge(lapa, laranjeiras)
G.add_edge(lapa, cidade_nova)


# txt = open(r"C:\Users\rasen\Documents\Programação\IC Iniciação Científica\Algoritmos Grafos\RJ\comandos.txt", "w")
# tt = TextTransform(r"C:\Users\rasen\Documents\Programação\IC Iniciação Científica\Algoritmos Grafos\RJ\bairros apenas.txt", r"C:\Users\rasen\Documents\Programação\IC Iniciação Científica\Algoritmos Grafos\RJ\adjacencias.txt")

# txt.write(tt.NumCidades())
# txt.write(tt.AdjCidades())
nx.drawing.nx_pydot.write_dot(G, r"C:\Users\rasen\Documents\arquivo")

plt.figure(figsize=(10,8))

nx.draw(G, with_labels=True, font_weight='bold', font_size=6, node_size=100, clip_on=True)# pos,

plt.show()


